// Command specgen (re)generates docs/asyncapi/tau.yaml from the wire
// registries in internal/bridge (EventTypes, CommandTypes) plus the
// InitMessage struct. It is the only thing that should ever write that
// file's `components.schemas` section - hand edits get overwritten on the
// next run.
//
// Usage (from the repo root):
//
//	go -C tools run ./specgen
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"sort"

	"github.com/invopop/jsonschema"
	"gopkg.in/yaml.v3"

	"github.com/samcharles93/tau/internal/bridge"
)

func main() {
	repoRoot := flag.String("repo-root", "..", "path to the tau repo root")
	header := flag.String("header", "docs/asyncapi/header.yaml", "static AsyncAPI preamble, relative to repo-root")
	out := flag.String("out", "docs/asyncapi/tau.yaml", "output path, relative to repo-root")
	flag.Parse()

	if err := run(*repoRoot, *header, *out); err != nil {
		log.Fatalf("specgen: %v", err)
	}
}

func run(repoRoot, headerPath, outPath string) error {
	absRoot, err := filepath.Abs(repoRoot)
	if err != nil {
		return fmt.Errorf("resolve repo root: %w", err)
	}
	// AddGoComments joins base+dir textually to build import paths, so it
	// only works from clean relative paths - chdir so every path below is
	// relative to the repo root with no "..".
	if err := os.Chdir(absRoot); err != nil {
		return fmt.Errorf("chdir to repo root: %w", err)
	}

	reflector := &jsonschema.Reflector{
		ExpandedStruct: true,
		DoNotReference: false,
	}
	if err := reflector.AddGoComments("github.com/samcharles93/tau", "internal/chat"); err != nil {
		return fmt.Errorf("load doc comments: %w", err)
	}

	schemas := map[string]any{}
	collect := func(name string, t reflect.Type) error {
		return collectSchema(reflector, schemas, name, t)
	}

	for _, e := range bridge.EventTypes {
		if err := collect(e.Name, e.Type); err != nil {
			return fmt.Errorf("reflect %s: %w", e.Name, err)
		}
	}
	for _, c := range bridge.CommandTypes {
		if err := collect(c.Name, c.Type); err != nil {
			return fmt.Errorf("reflect %s: %w", c.Name, err)
		}
	}
	if err := collect("InitMessage", reflect.TypeFor[bridge.InitMessage]()); err != nil {
		return fmt.Errorf("reflect InitMessage: %w", err)
	}

	rewriteDefRefs(schemas)

	schemas["ChatEventEnvelope"] = envelopeSchema(
		"Concrete ChatEvent type name (e.g. ChatResponseDeltaEvent).",
		refList(bridge.EventTypes, func(e bridge.EventTypeInfo) string { return e.Name }),
	)
	schemas["ChatCommandEnvelope"] = envelopeSchema(
		"Concrete ChatCommand type name (e.g. SubmitChatPromptCommand).",
		refList(bridge.CommandTypes, func(c bridge.CommandTypeInfo) string { return c.Name }),
	)
	schemas["ErrorEnvelope"] = map[string]any{
		"type":     "object",
		"required": []any{"type", "payload"},
		"properties": map[string]any{
			"type":    map[string]any{"type": "string", "const": "error"},
			"payload": map[string]any{"type": "string", "description": "Human-readable error message."},
		},
	}

	headerBytes, err := os.ReadFile(headerPath)
	if err != nil {
		return fmt.Errorf("read header: %w", err)
	}
	var doc map[string]any
	if err := yaml.Unmarshal(headerBytes, &doc); err != nil {
		return fmt.Errorf("parse header: %w", err)
	}
	doc["components"] = map[string]any{"schemas": schemas}

	body, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("marshal spec: %w", err)
	}

	generatedHeader := "# Code generated by tools/specgen from internal/bridge.EventTypes / CommandTypes.\n" +
		"# DO NOT EDIT the components.schemas section by hand - run `go -C tools run ./specgen`.\n"

	if err := os.WriteFile(outPath, append([]byte(generatedHeader), body...), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}

	fmt.Printf("specgen: wrote %d schemas to %s\n", len(schemas), outPath)
	return nil
}

// collectSchema reflects t into a JSON schema, stores the root under name,
// and merges any nested named types it discovered ($defs) into schemas so
// they become their own top-level components.schemas entries.
func collectSchema(reflector *jsonschema.Reflector, schemas map[string]any, name string, t reflect.Type) error {
	if _, exists := schemas[name]; exists {
		return nil
	}
	s := reflector.ReflectFromType(t)
	raw, err := json.Marshal(s)
	if err != nil {
		return err
	}
	var tree map[string]any
	if err := json.Unmarshal(raw, &tree); err != nil {
		return err
	}
	defs, _ := tree["$defs"].(map[string]any)
	delete(tree, "$defs")
	delete(tree, "$schema")
	delete(tree, "$id")
	schemas[name] = tree
	for defName, defSchema := range defs {
		if _, exists := schemas[defName]; !exists {
			schemas[defName] = defSchema
		}
	}
	return nil
}

// rewriteDefRefs walks every schema and rewrites "#/$defs/X" refs (produced
// by the reflector) into "#/components/schemas/X" refs (AsyncAPI's convention).
func rewriteDefRefs(schemas map[string]any) {
	for name, schema := range schemas {
		schemas[name] = rewriteNode(schema)
	}
}

func rewriteNode(v any) any {
	switch n := v.(type) {
	case map[string]any:
		for k, val := range n {
			if k == "$ref" {
				if s, ok := val.(string); ok {
					n[k] = rewriteRef(s)
					continue
				}
			}
			n[k] = rewriteNode(val)
		}
		return n
	case []any:
		for i, val := range n {
			n[i] = rewriteNode(val)
		}
		return n
	default:
		return v
	}
}

func rewriteRef(ref string) string {
	const prefix = "#/$defs/"
	if len(ref) > len(prefix) && ref[:len(prefix)] == prefix {
		return "#/components/schemas/" + ref[len(prefix):]
	}
	return ref
}

func envelopeSchema(typeDescription string, refNames []string) map[string]any {
	sort.Strings(refNames)
	oneOf := make([]any, 0, len(refNames))
	for _, n := range refNames {
		oneOf = append(oneOf, map[string]any{"$ref": "#/components/schemas/" + n})
	}
	return map[string]any{
		"type":     "object",
		"required": []any{"type", "payload"},
		"properties": map[string]any{
			"type":    map[string]any{"type": "string", "description": typeDescription},
			"payload": map[string]any{"oneOf": oneOf},
		},
	}
}

func refList[T any](items []T, name func(T) string) []string {
	out := make([]string, 0, len(items))
	for _, it := range items {
		out = append(out, name(it))
	}
	return out
}
