// tau plugin wire contract.
//
// This file is the source of truth for the host<->plugin protocol. Both the
// tau host and every plugin binary compile against the Go code generated from
// it (pkg/plugin/api). Regenerate with `task proto`.
//
// Compatibility policy:
//   - Field, enum, and oneof numbers are append-only: never renumber or reuse
//     one. When removing a field, reserve its number and name.
//   - Evolve additively. Hosts skip unknown Widget/EventPayload kinds and
//     ignore unknown capability strings; plugins must tolerate absent fields
//     and Unimplemented host RPCs.
//   - A deliberate breaking change (package rename, field type change, enum
//     renumbering) must bump ProtocolVersion in api.Handshake so stale plugin
//     binaries are rejected at handshake instead of failing mid-call.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: tau/plugin/v1/extension.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExtensionService_GetMetadata_FullMethodName     = "/tau.plugin.v1.ExtensionService/GetMetadata"
	ExtensionService_RunCommand_FullMethodName      = "/tau.plugin.v1.ExtensionService/RunCommand"
	ExtensionService_Reload_FullMethodName          = "/tau.plugin.v1.ExtensionService/Reload"
	ExtensionService_DispatchEvent_FullMethodName   = "/tau.plugin.v1.ExtensionService/DispatchEvent"
	ExtensionService_GetTools_FullMethodName        = "/tau.plugin.v1.ExtensionService/GetTools"
	ExtensionService_ExecuteTool_FullMethodName     = "/tau.plugin.v1.ExtensionService/ExecuteTool"
	ExtensionService_Log_FullMethodName             = "/tau.plugin.v1.ExtensionService/Log"
	ExtensionService_Init_FullMethodName            = "/tau.plugin.v1.ExtensionService/Init"
	ExtensionService_GetCapabilities_FullMethodName = "/tau.plugin.v1.ExtensionService/GetCapabilities"
)

// ExtensionServiceClient is the client API for ExtensionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtensionServiceClient interface {
	GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error)
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	DispatchEvent(ctx context.Context, in *DispatchEventRequest, opts ...grpc.CallOption) (*DispatchEventResponse, error)
	GetTools(ctx context.Context, in *GetToolsRequest, opts ...grpc.CallOption) (*GetToolsResponse, error)
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Init hands the plugin the broker id of the host's HostService so the
	// plugin can dial back. Called once by the host right after handshake.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// GetCapabilities reports which capability types the plugin provides so the
	// host can skip unsupported calls and evolve the protocol additively.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type extensionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExtensionServiceClient(cc grpc.ClientConnInterface) ExtensionServiceClient {
	return &extensionServiceClient{cc}
}

func (c *extensionServiceClient) GetMetadata(ctx context.Context, in *GetMetadataRequest, opts ...grpc.CallOption) (*GetMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetadataResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, ExtensionService_RunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, ExtensionService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) DispatchEvent(ctx context.Context, in *DispatchEventRequest, opts ...grpc.CallOption) (*DispatchEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchEventResponse)
	err := c.cc.Invoke(ctx, ExtensionService_DispatchEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) GetTools(ctx context.Context, in *GetToolsRequest, opts ...grpc.CallOption) (*GetToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToolsResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, ExtensionService_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, ExtensionService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ExtensionService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extensionServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, ExtensionService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtensionServiceServer is the server API for ExtensionService service.
// All implementations must embed UnimplementedExtensionServiceServer
// for forward compatibility.
type ExtensionServiceServer interface {
	GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error)
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	DispatchEvent(context.Context, *DispatchEventRequest) (*DispatchEventResponse, error)
	GetTools(context.Context, *GetToolsRequest) (*GetToolsResponse, error)
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// Init hands the plugin the broker id of the host's HostService so the
	// plugin can dial back. Called once by the host right after handshake.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// GetCapabilities reports which capability types the plugin provides so the
	// host can skip unsupported calls and evolve the protocol additively.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedExtensionServiceServer()
}

// UnimplementedExtensionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExtensionServiceServer struct{}

func (UnimplementedExtensionServiceServer) GetMetadata(context.Context, *GetMetadataRequest) (*GetMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedExtensionServiceServer) RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedExtensionServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedExtensionServiceServer) DispatchEvent(context.Context, *DispatchEventRequest) (*DispatchEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchEvent not implemented")
}
func (UnimplementedExtensionServiceServer) GetTools(context.Context, *GetToolsRequest) (*GetToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTools not implemented")
}
func (UnimplementedExtensionServiceServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedExtensionServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedExtensionServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedExtensionServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedExtensionServiceServer) mustEmbedUnimplementedExtensionServiceServer() {}
func (UnimplementedExtensionServiceServer) testEmbeddedByValue()                          {}

// UnsafeExtensionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtensionServiceServer will
// result in compilation errors.
type UnsafeExtensionServiceServer interface {
	mustEmbedUnimplementedExtensionServiceServer()
}

func RegisterExtensionServiceServer(s grpc.ServiceRegistrar, srv ExtensionServiceServer) {
	// If the following call panics, it indicates UnimplementedExtensionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExtensionService_ServiceDesc, srv)
}

func _ExtensionService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetMetadata(ctx, req.(*GetMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_RunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_DispatchEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).DispatchEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_DispatchEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).DispatchEvent(ctx, req.(*DispatchEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_GetTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetTools(ctx, req.(*GetToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtensionService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtensionServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExtensionService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtensionServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExtensionService_ServiceDesc is the grpc.ServiceDesc for ExtensionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExtensionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tau.plugin.v1.ExtensionService",
	HandlerType: (*ExtensionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _ExtensionService_GetMetadata_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _ExtensionService_RunCommand_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _ExtensionService_Reload_Handler,
		},
		{
			MethodName: "DispatchEvent",
			Handler:    _ExtensionService_DispatchEvent_Handler,
		},
		{
			MethodName: "GetTools",
			Handler:    _ExtensionService_GetTools_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _ExtensionService_ExecuteTool_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _ExtensionService_Log_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ExtensionService_Init_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _ExtensionService_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tau/plugin/v1/extension.proto",
}

const (
	HostService_GetConfig_FullMethodName          = "/tau.plugin.v1.HostService/GetConfig"
	HostService_SetConfig_FullMethodName          = "/tau.plugin.v1.HostService/SetConfig"
	HostService_GetSessionState_FullMethodName    = "/tau.plugin.v1.HostService/GetSessionState"
	HostService_GetAvailableModels_FullMethodName = "/tau.plugin.v1.HostService/GetAvailableModels"
	HostService_Notify_FullMethodName             = "/tau.plugin.v1.HostService/Notify"
	HostService_Log_FullMethodName                = "/tau.plugin.v1.HostService/Log"
	HostService_Confirm_FullMethodName            = "/tau.plugin.v1.HostService/Confirm"
	HostService_Input_FullMethodName              = "/tau.plugin.v1.HostService/Input"
	HostService_RenderView_FullMethodName         = "/tau.plugin.v1.HostService/RenderView"
	HostService_CloseView_FullMethodName          = "/tau.plugin.v1.HostService/CloseView"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is served by the tau host and called by plugins via the
// go-plugin broker. It gives plugins read access to host config/state and
// the ability to push notifications and structured logs back to tau.
type HostServiceClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResponse, error)
	GetAvailableModels(ctx context.Context, in *GetAvailableModelsRequest, opts ...grpc.CallOption) (*GetAvailableModelsResponse, error)
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error)
	Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error)
	RenderView(ctx context.Context, in *RenderViewRequest, opts ...grpc.CallOption) (*RenderViewResponse, error)
	CloseView(ctx context.Context, in *CloseViewRequest, opts ...grpc.CallOption) (*CloseViewResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, HostService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, HostService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStateResponse)
	err := c.cc.Invoke(ctx, HostService_GetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetAvailableModels(ctx context.Context, in *GetAvailableModelsRequest, opts ...grpc.CallOption) (*GetAvailableModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableModelsResponse)
	err := c.cc.Invoke(ctx, HostService_GetAvailableModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, HostService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, HostService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Confirm(ctx context.Context, in *ConfirmRequest, opts ...grpc.CallOption) (*ConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmResponse)
	err := c.cc.Invoke(ctx, HostService_Confirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) Input(ctx context.Context, in *InputRequest, opts ...grpc.CallOption) (*InputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputResponse)
	err := c.cc.Invoke(ctx, HostService_Input_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) RenderView(ctx context.Context, in *RenderViewRequest, opts ...grpc.CallOption) (*RenderViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderViewResponse)
	err := c.cc.Invoke(ctx, HostService_RenderView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) CloseView(ctx context.Context, in *CloseViewRequest, opts ...grpc.CallOption) (*CloseViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseViewResponse)
	err := c.cc.Invoke(ctx, HostService_CloseView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is served by the tau host and called by plugins via the
// go-plugin broker. It gives plugins read access to host config/state and
// the ability to push notifications and structured logs back to tau.
type HostServiceServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResponse, error)
	GetAvailableModels(context.Context, *GetAvailableModelsRequest) (*GetAvailableModelsResponse, error)
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error)
	Input(context.Context, *InputRequest) (*InputResponse, error)
	RenderView(context.Context, *RenderViewRequest) (*RenderViewResponse, error)
	CloseView(context.Context, *CloseViewRequest) (*CloseViewResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedHostServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedHostServiceServer) GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionState not implemented")
}
func (UnimplementedHostServiceServer) GetAvailableModels(context.Context, *GetAvailableModelsRequest) (*GetAvailableModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableModels not implemented")
}
func (UnimplementedHostServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedHostServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedHostServiceServer) Confirm(context.Context, *ConfirmRequest) (*ConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Confirm not implemented")
}
func (UnimplementedHostServiceServer) Input(context.Context, *InputRequest) (*InputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Input not implemented")
}
func (UnimplementedHostServiceServer) RenderView(context.Context, *RenderViewRequest) (*RenderViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderView not implemented")
}
func (UnimplementedHostServiceServer) CloseView(context.Context, *CloseViewRequest) (*CloseViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseView not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetSessionState(ctx, req.(*GetSessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetAvailableModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetAvailableModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetAvailableModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetAvailableModels(ctx, req.(*GetAvailableModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Confirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Confirm(ctx, req.(*ConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_Input_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).Input(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_Input_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).Input(ctx, req.(*InputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_RenderView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RenderView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RenderView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RenderView(ctx, req.(*RenderViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_CloseView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).CloseView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_CloseView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).CloseView(ctx, req.(*CloseViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tau.plugin.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _HostService_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _HostService_SetConfig_Handler,
		},
		{
			MethodName: "GetSessionState",
			Handler:    _HostService_GetSessionState_Handler,
		},
		{
			MethodName: "GetAvailableModels",
			Handler:    _HostService_GetAvailableModels_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _HostService_Notify_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _HostService_Log_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _HostService_Confirm_Handler,
		},
		{
			MethodName: "Input",
			Handler:    _HostService_Input_Handler,
		},
		{
			MethodName: "RenderView",
			Handler:    _HostService_RenderView_Handler,
		},
		{
			MethodName: "CloseView",
			Handler:    _HostService_CloseView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tau/plugin/v1/extension.proto",
}
