// Code generated by tui generate. DO NOT EDIT.
// Source: list.gsx

package components

import (
	"fmt"

	"github.com/grindlemire/go-tui"
	"github.com/samcharles93/tau/internal/theme"
)

type List struct {
	Items    *tui.State[[]ListItem]
	Selected *tui.State[int]
	OnSelect func(ListItem)
	focused  *tui.State[bool]
}

func NewList(items *tui.State[[]ListItem], selected *tui.State[int], onSelect func(ListItem)) *List {
	return &List{
		Items:    items,
		Selected: selected,
		OnSelect: onSelect,
		focused:  tui.NewState(false),
	}
}

func (l *List) BindApp(app *tui.App) {
	l.Items.BindApp(app)
	l.Selected.BindApp(app)
	l.focused.BindApp(app)
}

func (l *List) moveUp() {
	items := l.Items.Get()
	idx := l.Selected.Get()
	for range len(items) {
		idx--
		if idx < 0 {
			idx = len(items) - 1
		}
		if !items[idx].Disabled {
			l.Selected.Set(idx)
			return
		}
	}
}

func (l *List) moveDown() {
	items := l.Items.Get()
	idx := l.Selected.Get()
	for range len(items) {
		idx++
		if idx >= len(items) {
			idx = 0
		}
		if !items[idx].Disabled {
			l.Selected.Set(idx)
			return
		}
	}
}

func (l *List) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.KeyUp, func(tui.KeyEvent) { l.moveUp() }),
		tui.OnFocused(tui.KeyDown, func(tui.KeyEvent) { l.moveDown() }),
		tui.OnFocused(tui.KeyEnter, func(tui.KeyEvent) {
			items := l.Items.Get()
			idx := l.Selected.Get()
			if idx < 0 || idx >= len(items) {
				return
			}
			item := items[idx]
			if item.Disabled {
				return
			}
			if l.OnSelect != nil {
				l.OnSelect(item)
			}
		}),
	}
}

func (l *List) Focus() {
	l.focused.Set(true)
}

func (l *List) Blur() {
	l.focused.Set(false)
}

func (l *List) IsFocusable() bool {
	return true
}

func (l *List) IsTabStop() bool {
	return true
}

func (l *List) IsFocused() bool {
	return l.focused.Get()
}

func (l *List) HandleEvent(tui.Event) bool {
	return false
}

func init() {
	Register("list", func(app *tui.App) (tui.Component, []DebugControl) {
		items := tui.NewStateForApp(app, []ListItem{
			{ID: "a", Label: "Alpha", Description: "First option"},
			{ID: "b", Label: "Bravo", Description: "Second option"},
			{ID: "c", Label: "Charlie (Disabled)", Description: "Third option (skipped)", Disabled: true},
			{ID: "d", Label: "Delta", Description: "Fourth option"},
		})
		selected := tui.NewStateForApp(app, 0)
		comp := NewList(items, selected, nil)
		return comp, []DebugControl{
			{Label: "selected", Type: "text", State: intState(selected)},
		}
	})
}

func intState(s *tui.State[int]) *tui.State[string] {
	state := tui.NewState("0")
	s.Bind(func(v int) { state.Set(fmt.Sprintf("%d", v)) })
	return state
}

func (l *List) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithOnFocus(func(*tui.Element) { l.Focus() }),
		tui.WithOnBlur(func(*tui.Element) { l.Blur() }),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithAutoFocus(true),
	)
	for i, item := range l.Items.Get() {
		_ = i
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		if i == l.Selected.Get() {
			__tui_2 := tui.New(
				tui.WithText(item.Label),
				tui.WithTextStyle(theme.SelectedStyle()),
			)
			__tui_1.AddChild(__tui_2)
		} else if item.Disabled {
			__tui_3 := tui.New(
				tui.WithText(item.Label),
				tui.WithTextStyle(tui.NewStyle().Dim().Italic()),
			)
			__tui_1.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(item.Label),
			)
			__tui_1.AddChild(__tui_4)
		}
		if item.Description != "" {
			__tui_5 := tui.New(
				tui.WithText(" — "+item.Description),
				tui.WithTextStyle(tui.NewStyle().Dim().Italic()),
			)
			__tui_1.AddChild(__tui_5)
		}
		__tui_0.AddChild(__tui_1)
	}

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (l *List) bindAppFields(app *tui.App) {
	if l.Items != nil {
		l.Items.BindApp(app)
	}
	if l.Selected != nil {
		l.Selected.BindApp(app)
	}
	if l.focused != nil {
		l.focused.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*List)(nil)
)
