// Code generated by tui generate. DO NOT EDIT.
// Source: select.gsx

package components

import (
	"github.com/grindlemire/go-tui"
	"github.com/samcharles93/tau/internal/theme"
)

type Select struct {
	Value    *tui.State[string]
	Options  []SelectOption
	OnChange func(string)
	focused  *tui.State[bool]
}

func NewSelect(value *tui.State[string], options []SelectOption, onChange func(string)) *Select {
	return &Select{
		Value:    value,
		Options:  options,
		OnChange: onChange,
		focused:  tui.NewState(false),
	}
}

func (s *Select) currentLabel() string {
	v := s.Value.Get()
	for _, o := range s.Options {
		if o.Value == v {
			return o.Label
		}
	}
	return v
}

func (s *Select) currentIndex() int {
	v := s.Value.Get()
	for i, o := range s.Options {
		if o.Value == v {
			return i
		}
	}
	return -1
}

func (s *Select) BindApp(app *tui.App) {
	s.Value.BindApp(app)
	s.focused.BindApp(app)
}

func (s *Select) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.KeyLeft, func(tui.KeyEvent) {
			idx := s.currentIndex()
			if idx <= 0 {
				return
			}
			next := s.Options[idx-1]
			s.Value.Set(next.Value)
			if s.OnChange != nil {
				s.OnChange(next.Value)
			}
		}),
		tui.OnFocused(tui.KeyRight, func(tui.KeyEvent) {
			idx := s.currentIndex()
			if idx < 0 || idx >= len(s.Options)-1 {
				return
			}
			next := s.Options[idx+1]
			s.Value.Set(next.Value)
			if s.OnChange != nil {
				s.OnChange(next.Value)
			}
		}),
		tui.OnFocused(tui.KeyEnter, func(tui.KeyEvent) {
			// Retain focus on confirm
		}),
	}
}

func (s *Select) Focus() {
	s.focused.Set(true)
}

func (s *Select) Blur() {
	s.focused.Set(false)
}

func (s *Select) IsFocusable() bool {
	return true
}

func (s *Select) IsTabStop() bool {
	return true
}

func (s *Select) IsFocused() bool {
	return s.focused.Get()
}

func (s *Select) HandleEvent(tui.Event) bool {
	return false
}

func init() {
	Register("select", func(app *tui.App) (tui.Component, []DebugControl) {
		value := tui.NewStateForApp(app, "model-b")
		comp := NewSelect(value, []SelectOption{
			{Value: "model-a", Label: "GPT-4o"},
			{Value: "model-b", Label: "Claude Sonnet 4"},
			{Value: "model-c", Label: "Gemini 2.5 Pro"},
		}, nil)
		return comp, []DebugControl{
			{
				Label:   "value",
				Type:    "cycle",
				Options: []string{"model-a", "model-b", "model-c"},
				State:   value,
			},
		}
	})
}

func (s *Select) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(1),
		tui.WithBorder(tui.BorderSingle),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithOnFocus(func(*tui.Element) { s.Focus() }),
		tui.WithOnBlur(func(*tui.Element) { s.Blur() }),
		tui.WithAutoFocus(true),
	)
	__tui_1 := tui.New(
		tui.WithText("‹"),
		tui.WithTextStyle(tui.NewStyle().Dim().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	if s.focused.Get() {
		__tui_2 := tui.New(
			tui.WithText(s.currentLabel()),
			tui.WithTextStyle(theme.SelectedStyle()),
		)
		__tui_0.AddChild(__tui_2)
	} else {
		__tui_3 := tui.New(
			tui.WithText(s.currentLabel()),
		)
		__tui_0.AddChild(__tui_3)
	}
	__tui_4 := tui.New(
		tui.WithText("›"),
		tui.WithTextStyle(tui.NewStyle().Dim().Bold()),
	)
	__tui_0.AddChild(__tui_4)

	return __tui_0
}

func (s *Select) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*Select)
	if !ok {
		return
	}
	s.Options = f.Options
}

var _ tui.PropsUpdater = (*Select)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (s *Select) bindAppFields(app *tui.App) {
	if s.Value != nil {
		s.Value.BindApp(app)
	}
	if s.focused != nil {
		s.focused.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*Select)(nil)
)
