// Code generated by tui generate. DO NOT EDIT.
// Source: toggle.gsx

package components

import (
	"fmt"

	"github.com/grindlemire/go-tui"
	"github.com/samcharles93/tau/internal/theme"
)

type Toggle struct {
	Checked  *tui.State[bool]
	Label    string
	OnChange func(bool)
	focused  *tui.State[bool]
}

func NewToggle(checked *tui.State[bool], label string, onChange func(bool)) *Toggle {
	return &Toggle{
		Checked:  checked,
		Label:    label,
		OnChange: onChange,
		focused:  tui.NewState(false),
	}
}

func (t *Toggle) BindApp(app *tui.App) {
	t.Checked.BindApp(app)
	t.focused.BindApp(app)
}

func (t *Toggle) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.KeyEnter, func(tui.KeyEvent) { t.doFlip() }),
		tui.OnFocused(tui.Rune(' '), func(tui.KeyEvent) { t.doFlip() }),
	}
}

func (t *Toggle) doFlip() {
	next := !t.Checked.Get()
	t.Checked.Set(next)
	if t.OnChange != nil {
		t.OnChange(next)
	}
}

func (t *Toggle) Focus() {
	t.focused.Set(true)
}

func (t *Toggle) Blur() {
	t.focused.Set(false)
}

func (t *Toggle) IsFocusable() bool {
	return true
}

func (t *Toggle) IsTabStop() bool {
	return true
}

func (t *Toggle) IsFocused() bool {
	return t.focused.Get()
}

func (t *Toggle) HandleEvent(tui.Event) bool {
	return false
}

func init() {
	Register("toggle", func(app *tui.App) (tui.Component, []DebugControl) {
		checked := tui.NewStateForApp(app, true)
		comp := NewToggle(checked, "Show reasoning", nil)
		return comp, []DebugControl{
			{Label: "checked", Type: "toggle", State: boolState(checked)},
		}
	})
}

func boolState(s *tui.State[bool]) *tui.State[string] {
	state := tui.NewState(boolToStr(s.Get()))
	s.Bind(func(v bool) { state.Set(boolToStr(v)) })
	return state
}

func boolToStr(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

func strToBool(v string) bool {
	return v == "true"
}

func checkMark(checked bool) string {
	if checked {
		return "X"
	}
	return " "
}

func (t *Toggle) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithAlign(tui.AlignCenter),
		tui.WithGap(1),
		tui.WithPaddingTRBL(0, 1, 0, 1),
		tui.WithOnFocus(func(*tui.Element) { t.Focus() }),
		tui.WithOnBlur(func(*tui.Element) { t.Blur() }),
		tui.WithAutoFocus(true),
	)
	if t.focused.Get() {
		__tui_1 := tui.New(
			tui.WithText(fmt.Sprintf("[%s]", checkMark(t.Checked.Get()))),
			tui.WithTextStyle(theme.SelectedStyle()),
		)
		__tui_0.AddChild(__tui_1)
	} else {
		__tui_2 := tui.New(
			tui.WithText(fmt.Sprintf("[%s]", checkMark(t.Checked.Get()))),
		)
		__tui_0.AddChild(__tui_2)
	}
	__tui_3 := tui.New(
		tui.WithText(t.Label),
	)
	__tui_0.AddChild(__tui_3)

	return __tui_0
}

func (t *Toggle) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*Toggle)
	if !ok {
		return
	}
	t.Label = f.Label
}

var _ tui.PropsUpdater = (*Toggle)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (t *Toggle) bindAppFields(app *tui.App) {
	if t.Checked != nil {
		t.Checked.BindApp(app)
	}
	if t.focused != nil {
		t.focused.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*Toggle)(nil)
)
