// Code generated by tui generate. DO NOT EDIT.
// Source: tree.gsx

package components

import (
	"strings"

	"github.com/grindlemire/go-tui"
	"github.com/samcharles93/tau/internal/theme"
)

type Tree struct {
	Items    *tui.State[[]TreeItem]
	Selected *tui.State[int]
	OnSelect func(TreeItem)
	OnToggle func(TreeItem)
	OnDetail func(TreeItem)
	focused  *tui.State[bool]
}

func NewTree(items *tui.State[[]TreeItem], selected *tui.State[int], onSelect func(TreeItem), onToggle func(TreeItem), onDetail func(TreeItem)) *Tree {
	return &Tree{
		Items:    items,
		Selected: selected,
		OnSelect: onSelect,
		OnToggle: onToggle,
		OnDetail: onDetail,
		focused:  tui.NewState(false),
	}
}

func (t *Tree) BindApp(app *tui.App) {
	t.Items.BindApp(app)
	t.Selected.BindApp(app)
	t.focused.BindApp(app)
}

func (t *Tree) moveUp() {
	items := t.Items.Get()
	if len(items) == 0 {
		return
	}
	idx := t.Selected.Get() - 1
	if idx < 0 {
		idx = len(items) - 1
	}
	t.Selected.Set(idx)
}

func (t *Tree) moveDown() {
	items := t.Items.Get()
	if len(items) == 0 {
		return
	}
	idx := t.Selected.Get() + 1
	if idx >= len(items) {
		idx = 0
	}
	t.Selected.Set(idx)
}

func (t *Tree) handleLeft() {
	items := t.Items.Get()
	idx := t.Selected.Get()
	if idx < 0 || idx >= len(items) {
		return
	}
	item := items[idx]
	if item.HasChildren && item.Expanded {
		if t.OnToggle != nil {
			t.OnToggle(item)
		}
	}
}

func (t *Tree) handleRight() {
	items := t.Items.Get()
	idx := t.Selected.Get()
	if idx < 0 || idx >= len(items) {
		return
	}
	item := items[idx]
	if item.HasChildren && !item.Expanded {
		if t.OnToggle != nil {
			t.OnToggle(item)
		}
	} else {
		if t.OnDetail != nil {
			t.OnDetail(item)
		}
	}
}

func (t *Tree) handleEnter() {
	items := t.Items.Get()
	idx := t.Selected.Get()
	if idx < 0 || idx >= len(items) {
		return
	}
	item := items[idx]
	if item.HasChildren {
		if t.OnToggle != nil {
			t.OnToggle(item)
		}
	} else {
		if t.OnSelect != nil {
			t.OnSelect(item)
		}
	}
}

func (t *Tree) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnFocused(tui.KeyUp, func(tui.KeyEvent) { t.moveUp() }),
		tui.OnFocused(tui.KeyDown, func(tui.KeyEvent) { t.moveDown() }),
		tui.OnFocused(tui.KeyLeft, func(tui.KeyEvent) { t.handleLeft() }),
		tui.OnFocused(tui.KeyRight, func(tui.KeyEvent) { t.handleRight() }),
		tui.OnFocused(tui.KeyEnter, func(tui.KeyEvent) { t.handleEnter() }),
	}
}

func (t *Tree) Focus() {
	t.focused.Set(true)
}

func (t *Tree) Blur() {
	t.focused.Set(false)
}

func (t *Tree) IsFocusable() bool {
	return true
}

func (t *Tree) IsTabStop() bool {
	return true
}

func (t *Tree) IsFocused() bool {
	return t.focused.Get()
}

func (t *Tree) HandleEvent(tui.Event) bool {
	return false
}

func init() {
	Register("tree", func(app *tui.App) (tui.Component, []DebugControl) {
		items := tui.NewStateForApp(app, []TreeItem{
			{ID: "root", Label: "Root node", HasChildren: true, Expanded: true, Depth: 0},
			{ID: "child1", Label: "Child node 1", HasChildren: true, Expanded: false, Depth: 1},
			{ID: "grandchild", Label: "Grandchild", Depth: 2},
			{ID: "child2", Label: "Child node 2", Depth: 1},
		})
		selected := tui.NewStateForApp(app, 0)
		comp := NewTree(items, selected, nil, func(item TreeItem) {
			list := items.Get()
			for i, it := range list {
				if it.ID == item.ID {
					list[i].Expanded = !item.Expanded
					break
				}
			}
			items.Set(list)
		}, nil)
		return comp, []DebugControl{
			{Label: "selected", Type: "text", State: intState(selected)},
		}
	})
}

func (t *Tree) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithFlexGrow(1),
		tui.WithOnFocus(func(*tui.Element) { t.Focus() }),
		tui.WithOnBlur(func(*tui.Element) { t.Blur() }),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithAutoFocus(true),
	)
	for i, item := range t.Items.Get() {
		_ = i
		__tui_1 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithPaddingTRBL(0, 1, 0, 1),
		)
		__tui_2 := tui.New(
			tui.WithText(strings.Repeat("  ", item.Depth)),
		)
		__tui_1.AddChild(__tui_2)
		if item.HasChildren {
			if item.Expanded {
				__tui_3 := tui.New(
					tui.WithText("▼ "),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_1.AddChild(__tui_3)
			} else {
				__tui_4 := tui.New(
					tui.WithText("▶ "),
					tui.WithTextStyle(tui.NewStyle().Dim()),
				)
				__tui_1.AddChild(__tui_4)
			}
		} else {
			__tui_5 := tui.New(
				tui.WithText("  "),
			)
			__tui_1.AddChild(__tui_5)
		}
		if i == t.Selected.Get() {
			__tui_6 := tui.New(
				tui.WithText(item.Label),
				tui.WithTextStyle(theme.SelectedStyle()),
			)
			__tui_1.AddChild(__tui_6)
		} else {
			__tui_7 := tui.New(
				tui.WithText(item.Label),
			)
			__tui_1.AddChild(__tui_7)
		}
		if item.Description != "" {
			__tui_8 := tui.New(
				tui.WithText(" — "+item.Description),
				tui.WithTextStyle(tui.NewStyle().Dim().Italic()),
			)
			__tui_1.AddChild(__tui_8)
		}
		__tui_0.AddChild(__tui_1)
	}

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (t *Tree) bindAppFields(app *tui.App) {
	if t.Items != nil {
		t.Items.BindApp(app)
	}
	if t.Selected != nil {
		t.Selected.BindApp(app)
	}
	if t.focused != nil {
		t.focused.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*Tree)(nil)
)
