// Code generated by tui generate. DO NOT EDIT.
// Source: settings.gsx

package views

import (
	tui "github.com/grindlemire/go-tui"
	tauchat "github.com/samcharles93/tau/internal/chat"
	"github.com/samcharles93/tau/internal/theme"
)

type SettingsView struct {
	show               *tui.State[bool]
	provider           string
	modelName          *tui.State[string]
	availableModels    *tui.State[[]tauchat.ChatModelRef]
	selectedModelIndex *tui.State[int]
	showReasoning      *tui.State[bool]
	sessionID          func() string
	onSelectModel      func(string)
}

func NewSettingsView(
	show *tui.State[bool],
	provider string,
	modelName *tui.State[string],
	availableModels *tui.State[[]tauchat.ChatModelRef],
	selectedModelIndex *tui.State[int],
	showReasoning *tui.State[bool],
	sessionID func() string,
	onSelectModel func(string),
) *SettingsView {
	return &SettingsView{
		show:               show,
		provider:           provider,
		modelName:          modelName,
		availableModels:    availableModels,
		selectedModelIndex: selectedModelIndex,
		showReasoning:      showReasoning,
		sessionID:          sessionID,
		onSelectModel:      onSelectModel,
	}
}

func (v *SettingsView) BindApp(app *tui.App) {
	v.show.BindApp(app)
	v.modelName.BindApp(app)
	v.availableModels.BindApp(app)
	v.selectedModelIndex.BindApp(app)
	v.showReasoning.BindApp(app)
}

func (v *SettingsView) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) {
			v.show.Set(false)
		}),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) {
			models := v.availableModels.Get()
			if len(models) == 0 {
				return
			}
			idx := v.selectedModelIndex.Get() - 1
			if idx < 0 {
				idx = len(models) - 1
			}
			v.selectedModelIndex.Set(idx)
		}),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) {
			models := v.availableModels.Get()
			if len(models) == 0 {
				return
			}
			idx := v.selectedModelIndex.Get() + 1
			if idx >= len(models) {
				idx = 0
			}
			v.selectedModelIndex.Set(idx)
		}),
		tui.On(tui.KeyEnter, func(ke tui.KeyEvent) {
			models := v.availableModels.Get()
			if len(models) > 0 {
				idx := v.selectedModelIndex.Get()
				if idx >= 0 && idx < len(models) && models[idx].Ready {
					if v.onSelectModel != nil {
						v.onSelectModel(models[idx].ID)
					}
				}
			}
			v.showReasoning.Set(!v.showReasoning.Get())
		}),
	}
}

func (v *SettingsView) modelStyle(i int, model tauchat.ChatModelRef) tui.Style {
	currentModel := v.modelName.Get()
	selIdx := v.selectedModelIndex.Get()
	style := theme.DimStyle()
	if model.ID == currentModel {
		style = theme.BrandStyle()
	} else if i == selIdx && model.Ready {
		style = theme.BodyStyle()
	}
	if !model.Ready {
		style = theme.DimStyle().Italic()
	}
	return style
}

func (v *SettingsView) modelLabel(i int, model tauchat.ChatModelRef) string {
	currentModel := v.modelName.Get()
	selIdx := v.selectedModelIndex.Get()
	prefix := "  "
	if model.ID == currentModel {
		prefix = "✓ "
	} else if i == selIdx && model.Ready {
		prefix = "› "
	}
	label := prefix + model.ID
	if !model.Ready {
		label += " (not ready)"
	}
	return label
}

func (v *SettingsView) Render(app *tui.App) *tui.Element {
	__tui_0 := app.MountPersistent(v, 0, func() tui.Component {
		return tui.NewModal(
			tui.WithModalOpen(v.show),
			tui.WithModalBackdrop("dim"),
			tui.WithModalTrapFocus(false),
			tui.WithModalElementOptions(tui.WithJustify(tui.JustifyCenter), tui.WithAlign(tui.AlignCenter)),
		)
	})
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidth(56),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithBorderStyle(theme.BrandStyle()),
	)
	__tui_2 := tui.New(
		tui.WithText("Settings"),
		tui.WithTextStyle(theme.BrandStyle()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("Provider: "+v.provider),
		tui.WithTextStyle(theme.BodyStyle()),
		tui.WithTruncate(true),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("Model: "+v.modelName.Get()),
		tui.WithTextStyle(theme.BodyStyle()),
		tui.WithTruncate(true),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithMaxHeight(12),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithGap(0),
	)
	for i, model := range v.availableModels.Get() {
		_ = i
		__tui_6 := tui.New(
			tui.WithText(v.modelLabel(i, model)),
			tui.WithTextStyle(v.modelStyle(i, model)),
			tui.WithTruncate(true),
		)
		__tui_5.AddChild(__tui_6)
	}
	__tui_1.AddChild(__tui_5)
	if v.showReasoning.Get() {
		__tui_7 := tui.New(
			tui.WithText("Reasoning: on  (↑↓ models  Enter switch/toggle  Ctrl+R)"),
			tui.WithTextStyle(theme.BodyStyle()),
			tui.WithTruncate(true),
		)
		__tui_1.AddChild(__tui_7)
	} else {
		__tui_8 := tui.New(
			tui.WithText("Reasoning: off  (↑↓ models  Enter switch/toggle  Ctrl+R)"),
			tui.WithTextStyle(theme.BodyStyle()),
			tui.WithTruncate(true),
		)
		__tui_1.AddChild(__tui_8)
	}
	if sid := v.sessionID(); sid != "" {
		__tui_9 := tui.New(
			tui.WithText("Session: "+sid),
			tui.WithTextStyle(theme.DimStyle()),
			tui.WithTruncate(true),
		)
		__tui_1.AddChild(__tui_9)
	}
	__tui_10 := tui.New(
		tui.WithText("↑↓: navigate models  Enter: switch/toggle  Esc: close"),
		tui.WithTextStyle(theme.DimStyle().Italic()),
	)
	__tui_1.AddChild(__tui_10)
	__tui_0.AddChild(__tui_1)

	return __tui_0
}

func (v *SettingsView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SettingsView)
	if !ok {
		return
	}
	v.provider = f.provider
}

var _ tui.PropsUpdater = (*SettingsView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (v *SettingsView) bindAppFields(app *tui.App) {
	if v.show != nil {
		v.show.BindApp(app)
	}
	if v.modelName != nil {
		v.modelName.BindApp(app)
	}
	if v.availableModels != nil {
		v.availableModels.BindApp(app)
	}
	if v.selectedModelIndex != nil {
		v.selectedModelIndex.BindApp(app)
	}
	if v.showReasoning != nil {
		v.showReasoning.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*SettingsView)(nil)
)
