name: Release please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: https://git.catlow.cloud/sam/release-please-action@v5.1.0
        with:
          gitea-host: git.catlow.cloud
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_TOKEN }}
          repo-url: sam/tau
          github-api-url: https://git.catlow.cloud/api/v1
          changelog-host: https://git.catlow.cloud